pipeline {
    agent any
    environment {
        github_url = 'https://github.com/saurabh-chamola/kubernetes.git'
        docker_username = 'saurabh0010'
    }
    parameters {
        string(name: 'BUILD_NUMBER', defaultValue: '1', description: 'Build number for versioning image')
    }
    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Code Checkout') {
            steps {
                git url: "${github_url}", branch: 'main'
            }
        }
        stage('Kubernetes File Update') {
            steps {
                script {
                    dir('backend') {
                        sh "sed -i 's|${docker_username}/wanderlust-beta-backend:.*|${docker_username}/wanderlust-beta-backend:${BUILD_NUMBER}|' kubernetes/backend.yaml"
                    }
                    dir('frontend') {
                        sh "sed -i 's|${docker_username}/wanderlust-beta-frontend:.*|${docker_username}/wanderlust-beta-frontend:${BUILD_NUMBER}|' kubernetes/frontend.yaml"
                    }
                }
            }
        }
          stage("Git: Code update and push to GitHub"){
            steps{
                script{
                    withCredentials([gitUsernamePassword(credentialsId: 'github-cred', gitToolName: 'Default')]) {
                        sh '''
                        echo "Checking repository status: "
                        git status
                    
                        echo "Adding changes to git: "
                        git add .
                        
                        echo "Commiting changes: "
                        git commit -m "Updated environment variables"
                        
                        echo "Pushing changes to github: "
                        git push https://github.com/saurabh-chamola/kubernetes.git main
                    '''
                    }
                }
            }
        }
    }
    }
}
